name: AbulaBostan
description: "Food Ordering App for Bostan Abula Spot."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #json_annotation: ^4.8.1
  #provider: ^6.1.1
  font_awesome_flutter: ^10.6.0
  #logger: ^2.0.2+1
  gap: ^3.0.1
  #carousel_slider: ^4.2.1
  #otp_text_field: ^1.1.3
  #choice: ^2.3.0
  #image_picker: ^0.8.7+5
  #intl: ^0.18.1
  #firebase_core: ^2.24.2
  #firebase_auth: ^4.16.0
  #cloud_firestore: ^4.14.0
  #google_sign_in: ^6.2.1
  #firebase_storage: ^11.6.0
  #cached_network_image: ^3.3.1
  #loading_animation_widget: ^1.2.0+4
  #email_validator: ^2.1.17
  #shared_preferences: ^2.2.2
  #flutter_launcher_icons: ^0.13.1
  #shimmer: ^3.0.0
  #bottom_sheet: ^4.0.0
  #syncfusion_flutter_gauges: ^24.1.47
  #url_launcher: ^6.2.4
  go_router: ^13.2.0
  sliding_clipped_nav_bar: ^3.1.0+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.jpg"
  min_sdk_android: 21


flutter:


  uses-material-design: true
  assets:
    - "assets/images/brand_identity/"
    - "assets/images/"


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoMedium.ttf
          weight: 500
        - asset: assets/fonts/NunitoRegular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Mulish
      fonts:
        - asset: assets/fonts/MulishItalicRegular.ttf
          weight: 400
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSansRomanRegular.ttf
          weight: 400
    - family: Rancho
      fonts:
        - asset: assets/fonts/RanchoRegular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoBlack.ttf
          weight: 900
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSansRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSansRomanExtraBold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratRomanRegular.ttf
          weight: 400
